const BASES = {
    USERS: '/users',
    PRODUCTS: '/products'
}

const IDS = {
    PRODUCT_ID: '/:productId',
    USER_ID: '/:userId'
}

export const ROUTES = {
    USERS : {
        BASE: BASES.USERS,
        EMPTY: '',
        ID: IDS.USER_ID,
        GET_ALL_USERS_RELATIONS: IDS.USER_ID + BASES.PRODUCTS,
        DELETE_ALL_USERS_RELATIONS: IDS.USER_ID + BASES.PRODUCTS,
        ADD_USERS_RELATIONS: IDS.USER_ID + BASES.PRODUCTS,
        DELETE_USERS_RELATION_BY_IDS: IDS.USER_ID + BASES.PRODUCTS + IDS.PRODUCT_ID
    },
    PRODUCTS : {
        BASE: BASES.PRODUCTS,
        EMPTY: '',
        ID: IDS.PRODUCT_ID,
        GET_ALL_PRODUCTS_RELATIONS: IDS.PRODUCT_ID + BASES.USERS,
        DELETE_ALL_PRODUCTS_RELATIONS: IDS.PRODUCT_ID + BASES.USERS,
        ADD_PRODUCTS_RELATIONS: IDS.PRODUCT_ID + BASES.USERS,
        DELETE_PRODUCTS_RELATION_BY_IDS: IDS.PRODUCT_ID + BASES.USERS + IDS.USER_ID
    }
}
